// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzflmcppfqndarrhlify.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6ZmxtY3BwZnFuZGFycmhsaWZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NzEwNjYsImV4cCI6MjA2NTQ0NzA2Nn0.agg4aj1oQrpB5zPh0lEWwGW6V4JI1Ln7cenS5tR-6j0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);